spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    kr.codesquad: DEBUG
    org.hibernate.type: TRACE
    com.amazonaws.util.EC2MetadataUtils: error
---
spring:
  sql:
    init:
      mode: always
